[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
moonzip = "544hmhQ5N72wv8aJFz92sgRMnDEqwmSuzGtG8T8CPgNb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
program-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/program/*.ts"
e2e-test = "yarn run ts-mocha --parallel -p ./tsconfig.json -t 1000000 tests/e2e/*.ts"

[test]
startup_wait = 10000

[test.validator]
rpc_port = 18899
bind_address = "solana-test-validator"
