version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "app-db"
      POSTGRES_USER: "app-adm"
      POSTGRES_PASSWORD: "app-adm-pass"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app-adm -d app-db"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  postgres:
    driver: bridge
  router:
    driver: bridge
volumes:
  postgres:
