version: "3.8"
services:
  postgres:
    image: postgres:16
    networks:
      - moonzip-dev
    environment:
      POSTGRES_DB: "app-db"
      POSTGRES_USER: "app-adm"
      POSTGRES_PASSWORD: "app-adm-pass"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app-adm -d app-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  helius-mock:
    image: moonzip/dev:latest
    command: [ "yarn", "helius-mock" ]
    networks:
      - moonzip-dev
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 4000" ]
      interval: 5s
      timeout: 5s
      retries: 5
  jito-mock:
    image: moonzip/dev:latest
    command: ["yarn", "jito-mock"]
    networks:
      - moonzip-dev
    environment:
      SOLANA_RPC: http://solana-test-validator:18899
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 13000"]
      interval: 5s
      timeout: 5s
      retries: 5
  pinata-mock:
    image: moonzip/dev:latest
    networks:
      - moonzip-dev
    command: ["yarn", "pinata-mock"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 14001"]
      interval: 5s
      timeout: 5s
      retries: 5
  pumpfun-mock:
    image: moonzip/dev:latest
    networks:
      - moonzip-dev
    command: ["yarn", "pumpfun-mock"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 14002"]
      interval: 5s
      timeout: 5s
      retries: 5
  solana-test-validator:
    image: moonzip/dev:latest
    command: ["bash", "./tests/utils/test_validator.sh"]
    networks:
      - moonzip-dev
    ports:
      - 18899:18899
      - 18900:18900
      - 10000:10000
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 18899"]
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    image: moonzip/dev:latest
    command: ["make", "db-migrate"]
    networks:
      - moonzip-dev
    environment:
      DATABASE_URL: postgres://app-adm:app-adm-pass@postgres:5432/app-db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
  app-migrator:
    image: moonzip/dev:latest
    command: ["bash", "./tests/utils/test_migrator.sh"]
    environment:
      DATABASE_URL: postgres://app-adm:app-adm-pass@postgres:5432/app-db?sslmode=disable
      APP_NAME: migrator
      APP_RUN_MODE: test
    networks:
      - moonzip-dev
    depends_on:
      migration:
        condition: service_completed_successfully
      solana-test-validator:
        condition: service_healthy
      pinata-mock:
        condition: service_healthy
      pumpfun-mock:
        condition: service_healthy
      jito-mock:
        condition: service_healthy
      helius-mock:
        condition: service_healthy
      app-chain-syncer:
        condition: service_started
  app-chain-syncer:
    image: moonzip/dev:latest
    command: ["chain_syncer"]
    environment:
      DATABASE_URL: postgres://app-adm:app-adm-pass@postgres:5432/app-db?sslmode=disable
      APP_NAME: chain_syncer
      APP_RUN_MODE: test
    networks:
      - moonzip-dev
    depends_on:
      migration:
        condition: service_completed_successfully
      solana-test-validator:
        condition: service_healthy

  app-api:
    image: moonzip/dev:latest
    command: ["api_server"]
    environment:
      DATABASE_URL: postgres://app-adm:app-adm-pass@postgres:5432/app-db?sslmode=disable
      APP_NAME: api_server
      APP_RUN_MODE: test
    networks:
      - moonzip-dev
    depends_on:
      app-migrator:
        condition: service_started
      solana-test-validator:
        condition: service_healthy
      helius-mock:
        condition: service_healthy
volumes:
  postgres:
networks:
  moonzip-dev:
    driver: bridge
