FROM backpackapp/build:v0.30.1

RUN export DEBIAN_FRONTEND=noninteractive && apt install -y make
RUN rustup default 1.81.0 && rustup component add rustfmt clippy && \
    cargo install sqlx-cli --no-default-features --features native-tls,postgres