name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/decr1x/moonzip-backend:main
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install yarn dependencies
        run: yarn install
      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/decr1x/moonzip-backend:main
      options: --user root

    steps:
      - uses: actions/checkout@v3

      - name: List rustup toolchains
        run: rustup toolchain list

      - name: Generate new keygen
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899

      - name: Check solana config
        run: solana config get

      - name: Install yarn dependencies
        run: yarn install

      - name: Run tests
        run: make test
