name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/decr1x/moonzip-back:0.1.3
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install yarn dependencies
        run: yarn install
      - name: Lint
        run: make lint

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/decr1x/moonzip-back:0.1.3
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install yarn dependencies
        run: yarn install
      - name: Unit test
        run: make unit-test

  ext-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build intermediate image
        uses: docker/bake-action@v6.3.0
        with:
          files: docker/bake.ci.hcl
          allow: "fs=/builds/mzip/backend"

      - name: Prepare environment
        run: docker compose -f dev/docker-compose.dev.yml up -d --wait || docker compose -f dev/docker-compose.dev.yml logs

      - name: Run tests
        run: make ext-test
